Natsu/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Natsu.DbContexts;
using Natsu.Helpers;

namespace Natsu.Controllers
{
	public class CartController : Controller
	{
		private readonly ApplicationDbContext _context; // Your DbContext

		public CartController(ApplicationDbContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			var cart = SessionCart.GetCart(HttpContext);
			return View(cart);
		}

		public IActionResult AddToCart(int productId, int quantity)
		{
			var product = _context.products.Find(productId);
			if (product == null) return NotFound();

			var cart = SessionCart.GetCart(HttpContext);
			cart.AddItem(product, quantity);
			SessionCart.SaveCart(HttpContext, cart);

			return RedirectToAction("Index");
		}

		public IActionResult RemoveFromCart(int productId)
		{
			var cart = SessionCart.GetCart(HttpContext);
			cart.RemoveItem(productId);
			SessionCart.SaveCart(HttpContext, cart);

			return RedirectToAction("Index");
		}

		public IActionResult ClearCart()
		{
			var cart = SessionCart.GetCart(HttpContext);
			cart.Clear();
			SessionCart.SaveCart(HttpContext, cart);

			return RedirectToAction("Index");
		}
	}

}

Natsu/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Natsu.DbContexts;
using Natsu.Models;

namespace Natsu.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]

        public IActionResult GetIndexView()
        {
            return View("Index", _context.categories.ToList());
        }

        [HttpGet]

        public IActionResult GetCreateView()
        {
            ViewBag.AllCategories = _context.categories.ToList();
            return View("Create");
        }

        [HttpGet]

        public IActionResult GetDetailsView(int id)
        {

            var category = _context.categories.Include(prod => prod.Products).FirstOrDefault(prod1 => prod1.Id == id);
            if (category == null)
            {
                return
                    NotFound();
            }
            else
            {
                return View("Details", category);
            }
        }
        [HttpPost]
        public IActionResult Add(Category category)
        {
            _context.categories.Add(category);
            _context.SaveChanges();
            return RedirectToAction("GetIndexView");
        }

        // Edit category (GET)
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var category = _context.categories.FirstOrDefault(c => c.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View("Edit", category);
        }

        // Edit category (POST)
        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _context.categories.Update(category);
                _context.SaveChanges();
                return RedirectToAction("GetIndexView");
            }

            return View("Edit", category);
        }

        // Delete category (GET)
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var category = _context.categories.FirstOrDefault(c => c.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View("Delete", category);
        }

        // Delete category (POST)
        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            var category = _context.categories.FirstOrDefault(c => c.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            _context.categories.Remove(category);
            _context.SaveChanges();
            return RedirectToAction("GetIndexView");
        }
    }
}

Natsu/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Natsu.DbContexts;
using Natsu.Models;

namespace Natsu.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;


        public ProductsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;

        }
        // Http verbs : httpGet httpPost
        [HttpGet]

        public IActionResult GetCreateView()
        {
            ViewBag.AllCategories = _context.categories.ToList();
            return View("Create");
        }
        [HttpGet]

        //collections
        public IActionResult View()
        {
            return View("view", _context.products.ToList());

        }
        [HttpGet]

        //product
        public IActionResult GetIndexView()
        {
            return View("Index", _context.products.ToList());
        }
        
        
        [HttpGet]

        public IActionResult GetDetailsView(int id)
        {
            Product product = _context.products.Include(prod => prod.Category).FirstOrDefault(prod1 => prod1.Id == id);
            if (product == null)
            {
                return
                    NotFound();
            }
            else
            {
                return View("Details", product);
            }
        }
        [HttpPost]
        public IActionResult AddNew(Product product)
        {
       
            if (ModelState.IsValid == true)
            {
                if (product.ImageFile == null)
                {
                    product.ImagePath = "\\images\\No_image.png";
                }
                else
                {
                    
                    Guid imgGuid = Guid.NewGuid();
                    string imgExtinsion = Path.GetExtension(product.ImageFile.FileName);
                    string imagePath = "\\images\\" + imgGuid + imgExtinsion;
                    string imgFullPath = _webHostEnvironment.WebRootPath + imagePath;
                    FileStream fileStream = new FileStream(imgFullPath, FileMode.Create);
                    product.ImageFile.CopyTo(fileStream);
                    fileStream.Dispose();
                    product.ImagePath = imagePath;

                }

             

                _context.products.Add(product);
                _context.SaveChanges();
                return RedirectToAction("GetIndexView");
            }
            else
            {
                ViewBag.AllCategories = _context.categories.ToList();
                return View("Create");
            }
        }

        [HttpGet]

        public IActionResult GetDeleteView(int id)
        {
            Product product = _context.products.Include(prod => prod.Category).FirstOrDefault(prod => prod.Id == id);
            if (product == null)
            {
                return
                    NotFound();
            }
            else
            {
                return View("Delete", product);
            }



        }

        [HttpPost]
        public IActionResult DeleteCurrent(int Id)
        {
            // Find()-> only search for prymary keys but it's really fast as it get data direcrly from memory

            Product product = _context.products.Find(Id);
            // fully qualified name
            if (product.ImagePath != "\\images\\No_Image.png")
            {
                if (System.IO.File.Exists(product.ImagePath))

                {
                    System.IO.File.Delete(product.ImagePath);
                }
            }
            _context.products.Remove(product);
            _context.SaveChanges();
            return RedirectToAction("GetIndexView");

        }
        [HttpGet]

        public IActionResult GetEditView(int id)
        {
            Product product = _context.products.Find(id);
            if (product == null)
            {
                return
                    NotFound();
            }
            else
            {
                ViewBag.AllCategories = _context.categories.ToList();
                return View("Edit", product);
            }

        }

       

        [HttpPost]
        public IActionResult EditCurrent(Product product)
        {
            if (ModelState.IsValid == true)
            {
                if (product.ImageFile != null)
                {
                    if (product.ImagePath != "\\images\\No_Image.png")
                    {
                        if (System.IO.File.Exists(_webHostEnvironment.WebRootPath + product.ImagePath) == true)
                        {
                            System.IO.File.Delete(_webHostEnvironment.WebRootPath + product.ImagePath);
                        }
                    }

                    Guid imgGuid = Guid.NewGuid();
                    string imgExtension = Path.GetExtension(product.ImageFile.FileName);
                    string imgPath = "\\images\\" + imgGuid + imgExtension;
                    product.ImagePath = imgPath;
                    string imgFullPath = _webHostEnvironment.WebRootPath + imgPath;
                    FileStream fileStream = new FileStream(imgFullPath, FileMode.Create);
                    product.ImageFile.CopyTo(fileStream);
                    fileStream.Dispose();
                }

              
                _context.products.Update(product);
                _context.SaveChanges();
                return RedirectToAction("GetIndexView");
            }
            else
            {
                ViewBag.AllCategories = _context.categories.ToList();
                return View("Edit");
            }
        }
    }
}

Natsu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Natsu</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Natsu.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Natsu</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="GetIndexView">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="GetIndexView">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="view">View</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cart" asp-action="Index" title="list">
                                Cart
                            </a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer >
       
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>